# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2
jobs:
  build:
    docker:
      # https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/node:10-browsers

    working_directory: ~/repo

    steps:
      # checkout source code
      - checkout

      # download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # install node modules
      - run: yarn install

      # cache node modules
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run linters
      - run: yarn lint

      # build code
      - run: yarn build

      # run tests
      - run: yarn test
